### ISSUE TITLE
Cannot find module "ionic-native" when trying to run tutorial

### ISSUE THREAD

**Issue by ernesto-butto** [backand/ionic2-starter1#1]
Hello, I'm following the tutorial , however I can't get it to work, I'm getting a runtime error:
```
Cannot find module "ionic-native"
```

Tried to run 
```
npm install @ionic-native/core --save
```
But I'm still getting the same error.

Any suggestions ?
Thank you!

**Comment by kornatzky** [comment]
An additional dependency is needed:
    `npm install ionic-native`
The REAMDE was updated.
