### ISSUE TITLE
Version without social login

### ISSUE THREAD

**Issue by zorrobyte** [backand/ionic2-starter1#2]
I don't want to use Social Login and removing the code for this out of the starter can make it harder for Backand customers to start using the service.

**Comment by kornatzky** [comment]
it is very easy to remove the social. 

1. In `src/pages/login/login.ts` remove the function `socialSignin`
2. In `src/pages/login/login.html` remove section about the social networks.
3. In `src/pages/signup/signup.ts` remove the functions `socialWeb` and `inAppSocial`
4. In `src/pages/signup/signup.html` remove section about the social
